version: "3.1"

services:
  olympicker-postgres:
    container_name: olympicker-container-database
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - olympicker-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  olympicker-postgres: