version: "3.1"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "tp-spring"
      MYSQL_USER: "j2ee-tp-spring"
      MYQL_PASSWORD: "pwj2ee-tp-spring"
      MYSQL_ROOT_PASSWORD: "root"